create table if not exists drop_fee_distribution_runs (
  id bigint generated by default as identity primary key,
  mint text not null references drop_launches(mint) on delete cascade,
  claim_signature text,
  claim_ok boolean not null default false,
  claim_error text,
  claimed_lamports bigint not null default 0,
  whitelist_lamports_sent bigint not null default 0,
  holders_lamports_sent bigint not null default 0,
  total_sent_lamports bigint not null default 0,
  whitelist_transfers_sent int not null default 0,
  holder_transfers_sent int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists drop_fee_distribution_runs_mint_idx
  on drop_fee_distribution_runs (mint);

create index if not exists drop_fee_distribution_runs_created_at_idx
  on drop_fee_distribution_runs (created_at desc);

